# # 首次运行前初始化数据库
# docker-compose run web python init_db.py

# # 启动应用
# docker-compose up

# # 访问应用
# http://localhost:5000

version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./wsgi.py:/app/wsgi.py
      - ./init_db.py:/app/init_db.py
      - ./requirements.txt:/app/requirements.txt
      - ./instance:/app/instance
    environment:
      FLASK_APP: wsgi.py
      FLASK_ENV: development
    command: python wsgi.py